//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nipendo.Common.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum dvd_carState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// 
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("dvd_car")]
	public partial class dvd_car : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string dvd_car_manu = "dvd_car_manu";
			public const string dvd_car_model = "dvd_car_model";
			public const string dvd_carId = "dvd_carid";
			public const string Id = "dvd_carid";
			public const string dvd_datetoendlicense = "dvd_datetoendlicense";
			public const string dvd_doornum = "dvd_doornum";
			public const string dvd_enginevol = "dvd_enginevol";
			public const string dvd_firstdateonroad = "dvd_firstdateonroad";
			public const string dvd_gastype = "dvd_gastype";
			public const string dvd_kilometraj = "dvd_kilometraj";
			public const string dvd_kmtonextmaintence = "dvd_kmtonextmaintence";
			public const string dvd_manuyear = "dvd_manuyear";
			public const string dvd_Name = "dvd_name";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string dvd_dvd_car_car_manu_dvd_manu = "dvd_dvd_car_car_manu_dvd_manu";
			public const string dvd_dvd_car_car_model_dvd_mod = "dvd_dvd_car_car_model_dvd_mod";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public dvd_car() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "dvd_car";
		
		public const string EntitySchemaName = "dvd_car";
		
		public const string PrimaryIdAttribute = "dvd_carid";
		
		public const string PrimaryNameAttribute = "dvd_name";
		
		public const string EntityLogicalCollectionName = "dvd_cars";
		
		public const string EntitySetName = "dvd_cars";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// המזהה הייחודי של המשתמש שיצר את הרשומה.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// התאריך והשעה שבהם נוצרה הרשומה.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// המזהה הייחודי של המשתמש הנציג שיצר את הרשומה.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_car_manu")]
		public Microsoft.Xrm.Sdk.EntityReference dvd_car_manu
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dvd_car_manu");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_car_manu");
				this.SetAttributeValue("dvd_car_manu", value);
				this.OnPropertyChanged("dvd_car_manu");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_car_model")]
		public Microsoft.Xrm.Sdk.EntityReference dvd_car_model
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dvd_car_model");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_car_model");
				this.SetAttributeValue("dvd_car_model", value);
				this.OnPropertyChanged("dvd_car_model");
			}
		}
		
		/// <summary>
		/// המזהה הייחודי של מופעי ישות
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_carid")]
		public System.Nullable<System.Guid> dvd_carId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("dvd_carid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_carId");
				this.SetAttributeValue("dvd_carid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("dvd_carId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_carid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.dvd_carId = value;
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_datetoendlicense")]
		public System.Nullable<System.DateTime> dvd_datetoendlicense
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dvd_datetoendlicense");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_datetoendlicense");
				this.SetAttributeValue("dvd_datetoendlicense", value);
				this.OnPropertyChanged("dvd_datetoendlicense");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_doornum")]
		public Microsoft.Xrm.Sdk.OptionSetValue dvd_doornum
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("dvd_doornum");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_doornum");
				this.SetAttributeValue("dvd_doornum", value);
				this.OnPropertyChanged("dvd_doornum");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_enginevol")]
		public string dvd_enginevol
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dvd_enginevol");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_enginevol");
				this.SetAttributeValue("dvd_enginevol", value);
				this.OnPropertyChanged("dvd_enginevol");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_firstdateonroad")]
		public System.Nullable<System.DateTime> dvd_firstdateonroad
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("dvd_firstdateonroad");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_firstdateonroad");
				this.SetAttributeValue("dvd_firstdateonroad", value);
				this.OnPropertyChanged("dvd_firstdateonroad");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_gastype")]
		public Microsoft.Xrm.Sdk.OptionSetValue dvd_gastype
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("dvd_gastype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_gastype");
				this.SetAttributeValue("dvd_gastype", value);
				this.OnPropertyChanged("dvd_gastype");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_kilometraj")]
		public System.Nullable<int> dvd_kilometraj
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dvd_kilometraj");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_kilometraj");
				this.SetAttributeValue("dvd_kilometraj", value);
				this.OnPropertyChanged("dvd_kilometraj");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_kmtonextmaintence")]
		public System.Nullable<int> dvd_kmtonextmaintence
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("dvd_kmtonextmaintence");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_kmtonextmaintence");
				this.SetAttributeValue("dvd_kmtonextmaintence", value);
				this.OnPropertyChanged("dvd_kmtonextmaintence");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_manuyear")]
		public Microsoft.Xrm.Sdk.OptionSetValue dvd_manuyear
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("dvd_manuyear");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_manuyear");
				this.SetAttributeValue("dvd_manuyear", value);
				this.OnPropertyChanged("dvd_manuyear");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_name")]
		public string dvd_Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("dvd_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_Name");
				this.SetAttributeValue("dvd_name", value);
				this.OnPropertyChanged("dvd_Name");
			}
		}
		
		/// <summary>
		/// מספר הרצף של הייבוא שיצר את הרשומה.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// המזהה הייחודי של המשתמש ששינה את הרשומה.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// התאריך והשעה שבהם הרשומה השתנתה.‬‬
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// המזהה הייחודי של המשתמש הנציג ששינה את הרשומה.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// התאריך והשעה שבהם הועברה הרשומה.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// מזהה בעלים
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// המזהה הייחודי של היחידה העסקית שהרשומה נמצאת בבעלותה
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// ‏‏ה‏‏מזהה הייחודי של הצוות שהרשומה נמצאת בבעלותו.‬
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// המזהה הייחודי של המשתמש שהרשומה נמצאת בבעלותו.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// מצב הרכב
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Nipendo.Common.Entities.dvd_carState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Nipendo.Common.Entities.dvd_carState)(System.Enum.ToObject(typeof(Nipendo.Common.Entities.dvd_carState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// הסיבה למצב של הרכב
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// ‏‏לשימוש פנימי בלבד.‬
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// ‏‏קוד אזור הזמן שהיה בשימוש בעת יצירת הרשומה.‬
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// מספר גירסה
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N dvd_dvd_cardriver_cardriver_car_dvd_car
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dvd_dvd_cardriver_cardriver_car_dvd_car")]
		public System.Collections.Generic.IEnumerable<Nipendo.Common.Entities.dvd_cardriver> dvd_dvd_cardriver_cardriver_car_dvd_car
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Nipendo.Common.Entities.dvd_cardriver>("dvd_dvd_cardriver_cardriver_car_dvd_car", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_dvd_cardriver_cardriver_car_dvd_car");
				this.SetRelatedEntities<Nipendo.Common.Entities.dvd_cardriver>("dvd_dvd_cardriver_cardriver_car_dvd_car", null, value);
				this.OnPropertyChanged("dvd_dvd_cardriver_cardriver_car_dvd_car");
			}
		}
		
		/// <summary>
		/// 1:N dvd_incident_incident_car_dvd_car
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dvd_incident_incident_car_dvd_car")]
		public System.Collections.Generic.IEnumerable<Nipendo.Common.Entities.Incident> dvd_incident_incident_car_dvd_car
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Nipendo.Common.Entities.Incident>("dvd_incident_incident_car_dvd_car", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_incident_incident_car_dvd_car");
				this.SetRelatedEntities<Nipendo.Common.Entities.Incident>("dvd_incident_incident_car_dvd_car", null, value);
				this.OnPropertyChanged("dvd_incident_incident_car_dvd_car");
			}
		}
		
		/// <summary>
		/// 1:N dvd_opportunity_oppor_car_dvd_car
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dvd_opportunity_oppor_car_dvd_car")]
		public System.Collections.Generic.IEnumerable<Nipendo.Common.Entities.Opportunity> dvd_opportunity_oppor_car_dvd_car
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Nipendo.Common.Entities.Opportunity>("dvd_opportunity_oppor_car_dvd_car", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_opportunity_oppor_car_dvd_car");
				this.SetRelatedEntities<Nipendo.Common.Entities.Opportunity>("dvd_opportunity_oppor_car_dvd_car", null, value);
				this.OnPropertyChanged("dvd_opportunity_oppor_car_dvd_car");
			}
		}
		
		/// <summary>
		/// N:1 dvd_dvd_car_car_manu_dvd_manu
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_car_manu")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dvd_dvd_car_car_manu_dvd_manu")]
		public Nipendo.Common.Entities.dvd_manu dvd_dvd_car_car_manu_dvd_manu
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Nipendo.Common.Entities.dvd_manu>("dvd_dvd_car_car_manu_dvd_manu", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_dvd_car_car_manu_dvd_manu");
				this.SetRelatedEntity<Nipendo.Common.Entities.dvd_manu>("dvd_dvd_car_car_manu_dvd_manu", null, value);
				this.OnPropertyChanged("dvd_dvd_car_car_manu_dvd_manu");
			}
		}
		
		/// <summary>
		/// N:1 dvd_dvd_car_car_model_dvd_mod
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_car_model")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dvd_dvd_car_car_model_dvd_mod")]
		public Nipendo.Common.Entities.dvd_mod dvd_dvd_car_car_model_dvd_mod
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Nipendo.Common.Entities.dvd_mod>("dvd_dvd_car_car_model_dvd_mod", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_dvd_car_car_model_dvd_mod");
				this.SetRelatedEntity<Nipendo.Common.Entities.dvd_mod>("dvd_dvd_car_car_model_dvd_mod", null, value);
				this.OnPropertyChanged("dvd_dvd_car_car_model_dvd_mod");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public dvd_car(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["dvd_carid"] = base.Id;
                        break;
                    case "dvd_carid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}