//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace Nipendo.Common.Entities
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	public enum IncidentState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Resolved = 1,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Cancelled = 2,
	}
	
	/// <summary>
	/// אירוע בקשת השירות המשויך לחוזה.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("incident")]
	public partial class Incident : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public static class Fields
		{
			public const string AccountId = "accountid";
			public const string ActivitiesComplete = "activitiescomplete";
			public const string ActualServiceUnits = "actualserviceunits";
			public const string BilledServiceUnits = "billedserviceunits";
			public const string BlockedProfile = "blockedprofile";
			public const string caseage = "caseage";
			public const string CaseOriginCode = "caseorigincode";
			public const string CaseTypeCode = "casetypecode";
			public const string CheckEmail = "checkemail";
			public const string ContactId = "contactid";
			public const string ContractDetailId = "contractdetailid";
			public const string ContractId = "contractid";
			public const string ContractServiceLevelCode = "contractservicelevelcode";
			public const string CreatedBy = "createdby";
			public const string CreatedByExternalParty = "createdbyexternalparty";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string CustomerContacted = "customercontacted";
			public const string CustomerId = "customerid";
			public const string CustomerSatisfactionCode = "customersatisfactioncode";
			public const string deactivatedon = "deactivatedon";
			public const string DecrementEntitlementTerm = "decremententitlementterm";
			public const string Description = "description";
			public const string dvd_incident_car = "dvd_incident_car";
			public const string dvd_incident_cardriver = "dvd_incident_cardriver";
			public const string EmailAddress = "emailaddress";
			public const string EntitlementId = "entitlementid";
			public const string EntityImage = "entityimage";
			public const string EntityImage_Timestamp = "entityimage_timestamp";
			public const string EntityImage_URL = "entityimage_url";
			public const string EntityImageId = "entityimageid";
			public const string EscalatedOn = "escalatedon";
			public const string ExchangeRate = "exchangerate";
			public const string ExistingCase = "existingcase";
			public const string FirstResponseByKPIId = "firstresponsebykpiid";
			public const string FirstResponseSent = "firstresponsesent";
			public const string FirstResponseSLAStatus = "firstresponseslastatus";
			public const string FollowupBy = "followupby";
			public const string FollowUpTaskCreated = "followuptaskcreated";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string IncidentId = "incidentid";
			public const string Id = "incidentid";
			public const string IncidentStageCode = "incidentstagecode";
			public const string InfluenceScore = "influencescore";
			public const string IsDecrementing = "isdecrementing";
			public const string IsEscalated = "isescalated";
			public const string KbArticleId = "kbarticleid";
			public const string lastinteraction = "lastinteraction";
			public const string LastOnHoldTime = "lastonholdtime";
			public const string MasterId = "masterid";
			public const string Merged = "merged";
			public const string MessageTypeCode = "messagetypecode";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedByExternalParty = "modifiedbyexternalparty";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string msdyn_copilotengaged = "msdyn_copilotengaged";
			public const string msdyn_iotalert = "msdyn_iotalert";
			public const string msdyn_precreateattachmentsid = "msdyn_precreateattachmentsid";
			public const string msdyn_precreatenotesid = "msdyn_precreatenotesid";
			public const string nextsla = "nextsla";
			public const string NumberOfChildIncidents = "numberofchildincidents";
			public const string OnHoldTime = "onholdtime";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string ParentCaseId = "parentcaseid";
			public const string PrimaryContactId = "primarycontactid";
			public const string PriorityCode = "prioritycode";
			public const string ProcessId = "processid";
			public const string ProductId = "productid";
			public const string ProductSerialNumber = "productserialnumber";
			public const string ResolveBy = "resolveby";
			public const string ResolveByKPIId = "resolvebykpiid";
			public const string ResolveBySLAStatus = "resolvebyslastatus";
			public const string ResponseBy = "responseby";
			public const string ResponsibleContactId = "responsiblecontactid";
			public const string RouteCase = "routecase";
			public const string SentimentValue = "sentimentvalue";
			public const string ServiceStage = "servicestage";
			public const string SeverityCode = "severitycode";
			public const string SLAId = "slaid";
			public const string SLAInvokedId = "slainvokedid";
			public const string SocialProfileId = "socialprofileid";
			public const string StageId = "stageid";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string SubjectId = "subjectid";
			public const string TicketNumber = "ticketnumber";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string Title = "title";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string TraversedPath = "traversedpath";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string dvd_incident_incident_car_dvd_car = "dvd_incident_incident_car_dvd_car";
			public const string dvd_incident_incident_cardriver_dvd_cardriver = "dvd_incident_incident_cardriver_dvd_cardriver";
			public const string incident_customer_accounts = "incident_customer_accounts";
			public const string Referencingincident_existingcase = "incident_existingcase";
			public const string Referencingincident_master_incident = "incident_master_incident";
			public const string Referencingincident_parent_incident = "incident_parent_incident";
		}
		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public Incident() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "incident";
		
		public const string EntitySchemaName = "Incident";
		
		public const string PrimaryIdAttribute = "incidentid";
		
		public const string PrimaryNameAttribute = "title";
		
		public const string EntityLogicalCollectionName = "incidents";
		
		public const string EntitySetName = "incidents";
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// המזהה הייחודי של תיק הלקוח שאליו משויך האירוע.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("accountid")]
		public Microsoft.Xrm.Sdk.EntityReference AccountId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("accountid");
			}
		}
		
		/// <summary>
		/// תכונה זו משמשת לדוגמאות של תהליכים עסקיים של שירותים.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("activitiescomplete")]
		public System.Nullable<bool> ActivitiesComplete
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("activitiescomplete");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ActivitiesComplete");
				this.SetAttributeValue("activitiescomplete", value);
				this.OnPropertyChanged("ActivitiesComplete");
			}
		}
		
		/// <summary>
		/// הקלד את מספר יחידות השירות שנדרשו בפועל כדי לפתור את האירוע.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("actualserviceunits")]
		public System.Nullable<int> ActualServiceUnits
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("actualserviceunits");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ActualServiceUnits");
				this.SetAttributeValue("actualserviceunits", value);
				this.OnPropertyChanged("ActualServiceUnits");
			}
		}
		
		/// <summary>
		/// הקלד את מספר יחידות השירות שלפיהן חויב הלקוח עבור האירוע.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("billedserviceunits")]
		public System.Nullable<int> BilledServiceUnits
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("billedserviceunits");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BilledServiceUnits");
				this.SetAttributeValue("billedserviceunits", value);
				this.OnPropertyChanged("BilledServiceUnits");
			}
		}
		
		/// <summary>
		/// מפרט אם הפרופיל חסום או לא.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("blockedprofile")]
		public System.Nullable<bool> BlockedProfile
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("blockedprofile");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BlockedProfile");
				this.SetAttributeValue("blockedprofile", value);
				this.OnPropertyChanged("BlockedProfile");
			}
		}
		
		/// <summary>
		/// מציג את משך הזמן שבו האירוע היה פעיל עבור אירועים פעילים ואירועים שנפתרו.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("caseage")]
		public string caseage
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("caseage");
			}
		}
		
		/// <summary>
		/// בחר כיצד נוצר קשר לגבי האירוע, כגון דואר אלקטרוני, טלפון או אינטרנט, למטרות דיווח וניתוח.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("caseorigincode")]
		public Microsoft.Xrm.Sdk.OptionSetValue CaseOriginCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("caseorigincode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CaseOriginCode");
				this.SetAttributeValue("caseorigincode", value);
				this.OnPropertyChanged("CaseOriginCode");
			}
		}
		
		/// <summary>
		/// בחר את סוג האירוע כדי לזהות את המקרה למטרות ניתוב וניתוח של אירועים.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("casetypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue CaseTypeCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("casetypecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CaseTypeCode");
				this.SetAttributeValue("casetypecode", value);
				this.OnPropertyChanged("CaseTypeCode");
			}
		}
		
		/// <summary>
		/// תכונה זו משמשת לדוגמאות של תהליכים עסקיים של שירותים.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("checkemail")]
		public System.Nullable<bool> CheckEmail
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("checkemail");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CheckEmail");
				this.SetAttributeValue("checkemail", value);
				this.OnPropertyChanged("CheckEmail");
			}
		}
		
		/// <summary>
		/// המזהה הייחודי של איש הקשר המשויך לאירוע.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contactid")]
		public Microsoft.Xrm.Sdk.EntityReference ContactId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("contactid");
			}
		}
		
		/// <summary>
		/// בחר את סעיף החוזה שתחתיו יש לרשום את האירוע כדי לוודא שהלקוח מחויב בצורה נכונה.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contractdetailid")]
		public Microsoft.Xrm.Sdk.EntityReference ContractDetailId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("contractdetailid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ContractDetailId");
				this.SetAttributeValue("contractdetailid", value);
				this.OnPropertyChanged("ContractDetailId");
			}
		}
		
		/// <summary>
		/// בחר את חוזה השירות שתחתיו יש לרשום את האירוע כדי לוודא שהלקוח זכאי לשירותי תמיכה.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contractid")]
		public Microsoft.Xrm.Sdk.EntityReference ContractId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("contractid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ContractId");
				this.SetAttributeValue("contractid", value);
				this.OnPropertyChanged("ContractId");
			}
		}
		
		/// <summary>
		/// בחר את רמת השירות של האירוע כדי לוודא שהאירוע מטופל כראוי.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("contractservicelevelcode")]
		public Microsoft.Xrm.Sdk.OptionSetValue ContractServiceLevelCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("contractservicelevelcode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ContractServiceLevelCode");
				this.SetAttributeValue("contractservicelevelcode", value);
				this.OnPropertyChanged("ContractServiceLevelCode");
			}
		}
		
		/// <summary>
		/// מראה מי יצר את הרשומה.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Shows the external party who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdbyexternalparty")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedByExternalParty
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdbyexternalparty");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// מראה מי יצר את הרשומה בשמו של משתמש אחר.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// מציין אם נציג שירות לקוחות יצר קשר עם הלקוח או לא.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customercontacted")]
		public System.Nullable<bool> CustomerContacted
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("customercontacted");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CustomerContacted");
				this.SetAttributeValue("customercontacted", value);
				this.OnPropertyChanged("CustomerContacted");
			}
		}
		
		/// <summary>
		/// בחר את תיק הלקוח או איש הקשר של הלקוח כדי לספק קישור מהיר לפרטי לקוח נוספים, כגון פרטי חשבון, פעילויות והזדמנויות.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customerid")]
		public Microsoft.Xrm.Sdk.EntityReference CustomerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("customerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CustomerId");
				this.SetAttributeValue("customerid", value);
				this.OnPropertyChanged("CustomerId");
			}
		}
		
		/// <summary>
		/// בחר את רמת שביעות הרצון של הלקוח מהטיפול באירוע ופתרונו.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customersatisfactioncode")]
		public Microsoft.Xrm.Sdk.OptionSetValue CustomerSatisfactionCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("customersatisfactioncode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CustomerSatisfactionCode");
				this.SetAttributeValue("customersatisfactioncode", value);
				this.OnPropertyChanged("CustomerSatisfactionCode");
			}
		}
		
		/// <summary>
		/// מציג את התאריך והשעה שבהם האירוע נפתר.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("deactivatedon")]
		public System.Nullable<System.DateTime> deactivatedon
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("deactivatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("deactivatedon");
				this.SetAttributeValue("deactivatedon", value);
				this.OnPropertyChanged("deactivatedon");
			}
		}
		
		/// <summary>
		/// מראה אם יש להפחית את התנאים של הזכאות המשויכת או לא.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("decremententitlementterm")]
		public System.Nullable<bool> DecrementEntitlementTerm
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("decremententitlementterm");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("DecrementEntitlementTerm");
				this.SetAttributeValue("decremententitlementterm", value);
				this.OnPropertyChanged("DecrementEntitlementTerm");
			}
		}
		
		/// <summary>
		/// הקלד מידע נוסף כדי לתאר את האירוע במטרה לסייע לצוות השירות במציאת פתרון.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Description");
				this.SetAttributeValue("description", value);
				this.OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_incident_car")]
		public Microsoft.Xrm.Sdk.EntityReference dvd_incident_car
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dvd_incident_car");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_incident_car");
				this.SetAttributeValue("dvd_incident_car", value);
				this.OnPropertyChanged("dvd_incident_car");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_incident_cardriver")]
		public Microsoft.Xrm.Sdk.EntityReference dvd_incident_cardriver
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("dvd_incident_cardriver");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_incident_cardriver");
				this.SetAttributeValue("dvd_incident_cardriver", value);
				this.OnPropertyChanged("dvd_incident_cardriver");
			}
		}
		
		/// <summary>
		/// The primary email address for the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("emailaddress")]
		public string EmailAddress
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("emailaddress");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("EmailAddress");
				this.SetAttributeValue("emailaddress", value);
				this.OnPropertyChanged("EmailAddress");
			}
		}
		
		/// <summary>
		/// בחר את הזכאות הישימה עבור האירוע.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entitlementid")]
		public Microsoft.Xrm.Sdk.EntityReference EntitlementId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("entitlementid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("EntitlementId");
				this.SetAttributeValue("entitlementid", value);
				this.OnPropertyChanged("EntitlementId");
			}
		}
		
		/// <summary>
		/// תמונת ברירת המחדל עבור הישות.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage")]
		public byte[] EntityImage
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<byte[]>("entityimage");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("EntityImage");
				this.SetAttributeValue("entityimage", value);
				this.OnPropertyChanged("EntityImage");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_timestamp")]
		public System.Nullable<long> EntityImage_Timestamp
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("entityimage_timestamp");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimage_url")]
		public string EntityImage_URL
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("entityimage_url");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("entityimageid")]
		public System.Nullable<System.Guid> EntityImageId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("entityimageid");
			}
		}
		
		/// <summary>
		/// מציין את התאריך והשעה שבהם האירוע הוסלם.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("escalatedon")]
		public System.Nullable<System.DateTime> EscalatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("escalatedon");
			}
		}
		
		/// <summary>
		/// מציג את שער ההמרה של מטבע הרשומה. שער החליפין משמש להמרת כל שדות הכספים ברשומה מהמטבע המקומי למטבע ברירת המחדל של המערכת.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// בחר אירוע קיים עבור הלקוח שאוכלס. לשימוש פנימי בלבד.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("existingcase")]
		public Microsoft.Xrm.Sdk.EntityReference ExistingCase
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("existingcase");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ExistingCase");
				this.SetAttributeValue("existingcase", value);
				this.OnPropertyChanged("ExistingCase");
			}
		}
		
		/// <summary>
		/// ‏‏לשימוש פנימי בלבד.‬
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("firstresponsebykpiid")]
		public Microsoft.Xrm.Sdk.EntityReference FirstResponseByKPIId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("firstresponsebykpiid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("FirstResponseByKPIId");
				this.SetAttributeValue("firstresponsebykpiid", value);
				this.OnPropertyChanged("FirstResponseByKPIId");
			}
		}
		
		/// <summary>
		/// מציין אם התגובה הראשונה נשלחה.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("firstresponsesent")]
		public System.Nullable<bool> FirstResponseSent
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("firstresponsesent");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("FirstResponseSent");
				this.SetAttributeValue("firstresponsesent", value);
				this.OnPropertyChanged("FirstResponseSent");
			}
		}
		
		/// <summary>
		/// מציג את המצב של זמן התגובה הראשוני עבור האירוע בהתאם לתנאי ה- SLA.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("firstresponseslastatus")]
		public Microsoft.Xrm.Sdk.OptionSetValue FirstResponseSLAStatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("firstresponseslastatus");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("FirstResponseSLAStatus");
				this.SetAttributeValue("firstresponseslastatus", value);
				this.OnPropertyChanged("FirstResponseSLAStatus");
			}
		}
		
		/// <summary>
		/// הזן את התאריך שעד אליו נציג שירות לקוחות צריך לבצע את המשך הטיפול באירוע זה מול הלקוח.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("followupby")]
		public System.Nullable<System.DateTime> FollowupBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("followupby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("FollowupBy");
				this.SetAttributeValue("followupby", value);
				this.OnPropertyChanged("FollowupBy");
			}
		}
		
		/// <summary>
		/// תכונה זו משמשת לדוגמאות של תהליכים עסקיים של שירותים.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("followuptaskcreated")]
		public System.Nullable<bool> FollowUpTaskCreated
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("followuptaskcreated");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("FollowUpTaskCreated");
				this.SetAttributeValue("followuptaskcreated", value);
				this.OnPropertyChanged("FollowUpTaskCreated");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// המזהה הייחודי של האירוע.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("incidentid")]
		public System.Nullable<System.Guid> IncidentId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("incidentid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IncidentId");
				this.SetAttributeValue("incidentid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("IncidentId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("incidentid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.IncidentId = value;
			}
		}
		
		/// <summary>
		/// בחר את השלב הנוכחי של תהליך השירות עבור האירוע כדי לסייע לחברי צוות השירות כאשר הם סוקרים או מעבירים אירוע.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("incidentstagecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue IncidentStageCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("incidentstagecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IncidentStageCode");
				this.SetAttributeValue("incidentstagecode", value);
				this.OnPropertyChanged("IncidentStageCode");
			}
		}
		
		/// <summary>
		/// יכיל את ניקוד בעל ההשפעה המגיע מ- NetBreeze.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("influencescore")]
		public System.Nullable<double> InfluenceScore
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("influencescore");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("InfluenceScore");
				this.SetAttributeValue("influencescore", value);
				this.OnPropertyChanged("InfluenceScore");
			}
		}
		
		/// <summary>
		/// לשימוש המערכת בלבד.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isdecrementing")]
		public System.Nullable<bool> IsDecrementing
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isdecrementing");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IsDecrementing");
				this.SetAttributeValue("isdecrementing", value);
				this.OnPropertyChanged("IsDecrementing");
			}
		}
		
		/// <summary>
		/// מציין אם האירוע הוסלם.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isescalated")]
		public System.Nullable<bool> IsEscalated
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isescalated");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IsEscalated");
				this.SetAttributeValue("isescalated", value);
				this.OnPropertyChanged("IsEscalated");
			}
		}
		
		/// <summary>
		/// בחר את המאמר המכיל מידע נוסף או פתרון לאירוע, לצורך עיון במהלך מחקר או המשך טיפול מול הלקוח.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("kbarticleid")]
		public Microsoft.Xrm.Sdk.EntityReference KbArticleId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("kbarticleid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("KbArticleId");
				this.SetAttributeValue("kbarticleid", value);
				this.OnPropertyChanged("KbArticleId");
			}
		}
		
		/// <summary>
		/// מציג את הפעילות האחרונה ששויכה לאירוע ואת הפעולה שבוצעה בפעילות זו.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastinteraction")]
		public string lastinteraction
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("lastinteraction");
			}
		}
		
		/// <summary>
		/// מכיל את חותמת התאריך והשעה של זמן ההמתנה האחרון.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("lastonholdtime")]
		public System.Nullable<System.DateTime> LastOnHoldTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("lastonholdtime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("LastOnHoldTime");
				this.SetAttributeValue("lastonholdtime", value);
				this.OnPropertyChanged("LastOnHoldTime");
			}
		}
		
		/// <summary>
		/// בחר את האירוע הראשי שהאירוע הנוכחי מוזג לתוכו.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("masterid")]
		public Microsoft.Xrm.Sdk.EntityReference MasterId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("masterid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("MasterId");
				this.SetAttributeValue("masterid", value);
				this.OnPropertyChanged("MasterId");
			}
		}
		
		/// <summary>
		/// מציין אם המקרה מוזג עם מקרה אחר.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("merged")]
		public System.Nullable<bool> Merged
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("merged");
			}
		}
		
		/// <summary>
		/// מראה אם הפרסום נוצר כהודעה ציבורית או פרטית.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("messagetypecode")]
		public Microsoft.Xrm.Sdk.OptionSetValue MessageTypeCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("messagetypecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("MessageTypeCode");
				this.SetAttributeValue("messagetypecode", value);
				this.OnPropertyChanged("MessageTypeCode");
			}
		}
		
		/// <summary>
		/// מראה מי עדכן לאחרונה את הרשומה.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Shows the external party who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedbyexternalparty")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedByExternalParty
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedbyexternalparty");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// מראה מי עדכן לאחרונה את הרשומה בשמו של משתמש אחר.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_copilotengaged")]
		public System.Nullable<bool> msdyn_copilotengaged
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_copilotengaged");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_copilotengaged");
				this.SetAttributeValue("msdyn_copilotengaged", value);
				this.OnPropertyChanged("msdyn_copilotengaged");
			}
		}
		
		/// <summary>
		/// התראת ה- IoT שאתחלה אירוע זה
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_iotalert")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_iotalert
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_iotalert");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_iotalert");
				this.SetAttributeValue("msdyn_iotalert", value);
				this.OnPropertyChanged("msdyn_iotalert");
			}
		}
		
		/// <summary>
		/// מזהה קבצים מצורפים של ישות לפני יצירת רשומת האירוע
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_precreateattachmentsid")]
		public string msdyn_precreateattachmentsid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("msdyn_precreateattachmentsid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_precreateattachmentsid");
				this.SetAttributeValue("msdyn_precreateattachmentsid", value);
				this.OnPropertyChanged("msdyn_precreateattachmentsid");
			}
		}
		
		/// <summary>
		/// מזהה הערות לפני יצירת רשומת האירוע
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_precreatenotesid")]
		public string msdyn_precreatenotesid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("msdyn_precreatenotesid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_precreatenotesid");
				this.SetAttributeValue("msdyn_precreatenotesid", value);
				this.OnPropertyChanged("msdyn_precreatenotesid");
			}
		}
		
		/// <summary>
		/// מציג את ה- KPI של ה- SLA שלא נפתר המשויך לאירוע עם מועד התפוגה המוקדם ביותר.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("nextsla")]
		public string nextsla
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("nextsla");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("nextsla");
				this.SetAttributeValue("nextsla", value);
				this.OnPropertyChanged("nextsla");
			}
		}
		
		/// <summary>
		/// מספר מקרי הצאצא המשויכים למקרה.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("numberofchildincidents")]
		public System.Nullable<int> NumberOfChildIncidents
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("numberofchildincidents");
			}
		}
		
		/// <summary>
		/// מציג את המשך בדקות שבו האירוע היה בהמתנה.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("onholdtime")]
		public System.Nullable<int> OnHoldTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("onholdtime");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// בחר את אירוע האב של אירוע.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentcaseid")]
		public Microsoft.Xrm.Sdk.EntityReference ParentCaseId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("parentcaseid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ParentCaseId");
				this.SetAttributeValue("parentcaseid", value);
				this.OnPropertyChanged("ParentCaseId");
			}
		}
		
		/// <summary>
		/// בחר איש קשר ראשי עבור אירוע זה.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("primarycontactid")]
		public Microsoft.Xrm.Sdk.EntityReference PrimaryContactId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("primarycontactid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("PrimaryContactId");
				this.SetAttributeValue("primarycontactid", value);
				this.OnPropertyChanged("PrimaryContactId");
			}
		}
		
		/// <summary>
		/// בחר את העדיפות כך שלקוחות מועדפים או בעיות קריטיות יטופלו במהירות.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("prioritycode")]
		public Microsoft.Xrm.Sdk.OptionSetValue PriorityCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("prioritycode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("PriorityCode");
				this.SetAttributeValue("prioritycode", value);
				this.OnPropertyChanged("PriorityCode");
			}
		}
		
		/// <summary>
		/// Contains the id of the process associated with the entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> ProcessId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ProcessId");
				this.SetAttributeValue("processid", value);
				this.OnPropertyChanged("ProcessId");
			}
		}
		
		/// <summary>
		/// בחר את המוצר המשויך לאירוע כדי לזהות בעיות אחריות, בעיות שירות או בעיות אחרות במוצר ולאפשר דיווח על מספר המקרים לכל מוצר.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("productid")]
		public Microsoft.Xrm.Sdk.EntityReference ProductId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("productid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ProductId");
				this.SetAttributeValue("productid", value);
				this.OnPropertyChanged("ProductId");
			}
		}
		
		/// <summary>
		/// הקלד את המספר הסידורי של המוצר המשויך לאירוע זה, כך שניתן יהיה לדווח על מספר האירועים לכל מוצר.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("productserialnumber")]
		public string ProductSerialNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("productserialnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ProductSerialNumber");
				this.SetAttributeValue("productserialnumber", value);
				this.OnPropertyChanged("ProductSerialNumber");
			}
		}
		
		/// <summary>
		/// הזן את התאריך שעד אליו יש לפתור את האירוע.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resolveby")]
		public System.Nullable<System.DateTime> ResolveBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("resolveby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ResolveBy");
				this.SetAttributeValue("resolveby", value);
				this.OnPropertyChanged("ResolveBy");
			}
		}
		
		/// <summary>
		/// ‏‏לשימוש פנימי בלבד.‬
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resolvebykpiid")]
		public Microsoft.Xrm.Sdk.EntityReference ResolveByKPIId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("resolvebykpiid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ResolveByKPIId");
				this.SetAttributeValue("resolvebykpiid", value);
				this.OnPropertyChanged("ResolveByKPIId");
			}
		}
		
		/// <summary>
		/// מציג את המצב של זמן הפתרון עבור האירוע בהתאם לתנאי ה- SLA.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resolvebyslastatus")]
		public Microsoft.Xrm.Sdk.OptionSetValue ResolveBySLAStatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("resolvebyslastatus");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ResolveBySLAStatus");
				this.SetAttributeValue("resolvebyslastatus", value);
				this.OnPropertyChanged("ResolveBySLAStatus");
			}
		}
		
		/// <summary>
		/// ‏‏לשימוש פנימי בלבד.‬
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("responseby")]
		public System.Nullable<System.DateTime> ResponseBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("responseby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ResponseBy");
				this.SetAttributeValue("responseby", value);
				this.OnPropertyChanged("ResponseBy");
			}
		}
		
		/// <summary>
		/// בחר איש קשר נוסף של לקוח שיכול גם הוא לעזור לפתור את האירוע.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("responsiblecontactid")]
		[System.ObsoleteAttribute()]
		public Microsoft.Xrm.Sdk.EntityReference ResponsibleContactId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("responsiblecontactid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ResponsibleContactId");
				this.SetAttributeValue("responsiblecontactid", value);
				this.OnPropertyChanged("ResponsibleContactId");
			}
		}
		
		/// <summary>
		/// מציין אם המקרה נותב לתור או לא.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("routecase")]
		public System.Nullable<bool> RouteCase
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("routecase");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("RouteCase");
				this.SetAttributeValue("routecase", value);
				this.OnPropertyChanged("RouteCase");
			}
		}
		
		/// <summary>
		/// הערך שנגזר לאחר הערכת מילים המשויכות בדרך כלל לסנטימנט שלילי, ניטראלי או חיובי בפרסום חברתי. ניתן גם לדווח על פרטי סנטימנט כערכים מספריים.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("sentimentvalue")]
		public System.Nullable<double> SentimentValue
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("sentimentvalue");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SentimentValue");
				this.SetAttributeValue("sentimentvalue", value);
				this.OnPropertyChanged("SentimentValue");
			}
		}
		
		/// <summary>
		/// בחר את השלב שבו נמצא האירוע בתהליך פתרון האירוע.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("servicestage")]
		public Microsoft.Xrm.Sdk.OptionSetValue ServiceStage
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("servicestage");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ServiceStage");
				this.SetAttributeValue("servicestage", value);
				this.OnPropertyChanged("ServiceStage");
			}
		}
		
		/// <summary>
		/// בחר את חומרת אירוע זה כדי לציין את ההשפעה של המקרה על העסק של הלקוח.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("severitycode")]
		public Microsoft.Xrm.Sdk.OptionSetValue SeverityCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("severitycode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SeverityCode");
				this.SetAttributeValue("severitycode", value);
				this.OnPropertyChanged("SeverityCode");
			}
		}
		
		/// <summary>
		/// בחר את הסכם רמת השירות (SLA) שברצונך להחיל על רשומת האירוע.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slaid")]
		public Microsoft.Xrm.Sdk.EntityReference SLAId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("slaid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SLAId");
				this.SetAttributeValue("slaid", value);
				this.OnPropertyChanged("SLAId");
			}
		}
		
		/// <summary>
		/// ה- SLA האחרון שהוחל על אירוע זה. שדה זה מיועד לשימוש פנימי בלבד.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slainvokedid")]
		public Microsoft.Xrm.Sdk.EntityReference SLAInvokedId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("slainvokedid");
			}
		}
		
		/// <summary>
		/// המזהה הייחודי של הפרופיל החברתי שאליו משויך האירוע.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("socialprofileid")]
		public Microsoft.Xrm.Sdk.EntityReference SocialProfileId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("socialprofileid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SocialProfileId");
				this.SetAttributeValue("socialprofileid", value);
				this.OnPropertyChanged("SocialProfileId");
			}
		}
		
		/// <summary>
		/// Contains the id of the stage where the entity is located.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		public System.Nullable<System.Guid> StageId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StageId");
				this.SetAttributeValue("stageid", value);
				this.OnPropertyChanged("StageId");
			}
		}
		
		/// <summary>
		/// מראה אם האירוע פעיל, נפתר או בוטל. אירועים שנפתרו ואירועים שבוטלו מוגדרים לקריאה בלבד ולא ניתן לערוך אותם אלא אם הם מופעלים מחדש.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<Nipendo.Common.Entities.IncidentState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((Nipendo.Common.Entities.IncidentState)(System.Enum.ToObject(typeof(Nipendo.Common.Entities.IncidentState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// בחר את מצב האירוע.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public Microsoft.Xrm.Sdk.OptionSetValue StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// בחר את הנושא עבור האירוע, כגון בקשה לקטלוג או תלונה על מוצר, כך שמנהלי שירות לקוחות יוכלו לזהות בקשות תכופות או אזורים בעייתיים. מנהלי מערכת יכולים לקבוע את התצורה של נושאים תחת 'ניהול עסקי‬' באזור 'הגדרות'.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("subjectid")]
		public Microsoft.Xrm.Sdk.EntityReference SubjectId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("subjectid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SubjectId");
				this.SetAttributeValue("subjectid", value);
				this.OnPropertyChanged("SubjectId");
			}
		}
		
		/// <summary>
		/// מציג את מספר האירוע לצורך חיפוש ועיון בפרטי לקוחות. אין אפשרות לשנות זאת.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ticketnumber")]
		public string TicketNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("ticketnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TicketNumber");
				this.SetAttributeValue("ticketnumber", value);
				this.OnPropertyChanged("TicketNumber");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// הקלד נושא או שם תיאורי, כגון הבקשה, הבעיה או שם החברה, כדי לזהות את האירוע בתצוגות Microsoft Dynamics 365.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("title")]
		public string Title
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("title");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Title");
				this.SetAttributeValue("title", value);
				this.OnPropertyChanged("Title");
			}
		}
		
		/// <summary>
		/// בחר את המטבע המקומי עבור הרשומה כדי לוודא שתקציבים מדווחים במטבע הנכון.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// A comma separated list of string values representing the unique identifiers of stages in a Business Process Flow Instance in the order that they occur.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		public string TraversedPath
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TraversedPath");
				this.SetAttributeValue("traversedpath", value);
				this.OnPropertyChanged("TraversedPath");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N incident_existingcase
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<Nipendo.Common.Entities.Incident> Referencedincident_existingcase
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Nipendo.Common.Entities.Incident>("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencedincident_existingcase");
				this.SetRelatedEntities<Nipendo.Common.Entities.Incident>("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencedincident_existingcase");
			}
		}
		
		/// <summary>
		/// 1:N incident_master_incident
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<Nipendo.Common.Entities.Incident> Referencedincident_master_incident
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Nipendo.Common.Entities.Incident>("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencedincident_master_incident");
				this.SetRelatedEntities<Nipendo.Common.Entities.Incident>("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencedincident_master_incident");
			}
		}
		
		/// <summary>
		/// 1:N incident_parent_incident
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced)]
		public System.Collections.Generic.IEnumerable<Nipendo.Common.Entities.Incident> Referencedincident_parent_incident
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<Nipendo.Common.Entities.Incident>("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencedincident_parent_incident");
				this.SetRelatedEntities<Nipendo.Common.Entities.Incident>("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referenced, value);
				this.OnPropertyChanged("Referencedincident_parent_incident");
			}
		}
		
		/// <summary>
		/// N:1 dvd_incident_incident_car_dvd_car
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_incident_car")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dvd_incident_incident_car_dvd_car")]
		public Nipendo.Common.Entities.dvd_car dvd_incident_incident_car_dvd_car
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Nipendo.Common.Entities.dvd_car>("dvd_incident_incident_car_dvd_car", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_incident_incident_car_dvd_car");
				this.SetRelatedEntity<Nipendo.Common.Entities.dvd_car>("dvd_incident_incident_car_dvd_car", null, value);
				this.OnPropertyChanged("dvd_incident_incident_car_dvd_car");
			}
		}
		
		/// <summary>
		/// N:1 dvd_incident_incident_cardriver_dvd_cardriver
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("dvd_incident_cardriver")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("dvd_incident_incident_cardriver_dvd_cardriver")]
		public Nipendo.Common.Entities.dvd_cardriver dvd_incident_incident_cardriver_dvd_cardriver
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Nipendo.Common.Entities.dvd_cardriver>("dvd_incident_incident_cardriver_dvd_cardriver", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("dvd_incident_incident_cardriver_dvd_cardriver");
				this.SetRelatedEntity<Nipendo.Common.Entities.dvd_cardriver>("dvd_incident_incident_cardriver_dvd_cardriver", null, value);
				this.OnPropertyChanged("dvd_incident_incident_cardriver_dvd_cardriver");
			}
		}
		
		/// <summary>
		/// N:1 incident_customer_accounts
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("customerid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_customer_accounts")]
		public Nipendo.Common.Entities.Account incident_customer_accounts
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Nipendo.Common.Entities.Account>("incident_customer_accounts", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("incident_customer_accounts");
				this.SetRelatedEntity<Nipendo.Common.Entities.Account>("incident_customer_accounts", null, value);
				this.OnPropertyChanged("incident_customer_accounts");
			}
		}
		
		/// <summary>
		/// N:1 incident_existingcase
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("existingcase")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public Nipendo.Common.Entities.Incident Referencingincident_existingcase
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Nipendo.Common.Entities.Incident>("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencingincident_existingcase");
				this.SetRelatedEntity<Nipendo.Common.Entities.Incident>("incident_existingcase", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingincident_existingcase");
			}
		}
		
		/// <summary>
		/// N:1 incident_master_incident
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("masterid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public Nipendo.Common.Entities.Incident Referencingincident_master_incident
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Nipendo.Common.Entities.Incident>("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencingincident_master_incident");
				this.SetRelatedEntity<Nipendo.Common.Entities.Incident>("incident_master_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingincident_master_incident");
			}
		}
		
		/// <summary>
		/// N:1 incident_parent_incident
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("parentcaseid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing)]
		public Nipendo.Common.Entities.Incident Referencingincident_parent_incident
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<Nipendo.Common.Entities.Incident>("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Referencingincident_parent_incident");
				this.SetRelatedEntity<Nipendo.Common.Entities.Incident>("incident_parent_incident", Microsoft.Xrm.Sdk.EntityRole.Referencing, value);
				this.OnPropertyChanged("Referencingincident_parent_incident");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public Incident(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["incidentid"] = base.Id;
                        break;
                    case "incidentid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}